format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs

pipelines:
  'prm-deductions-generic-component':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
            integration:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_integration
            coverage:
              artifacts:
                - build:
                    source: coverage/lcov-report
              tabs:
                coverage: lcov-report/index.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_coverage
            build_artifacts:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: build_artifacts
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
      - test_docker:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_docker
  'prm-deductions-generic-component.dev':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-generic-component
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_functional
  'prm-deductions-generic-component.canary':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
    timer:
      spec: 0 12 14 ? * MON,TUE,WED,THU,FRI *
    stages:
      - audit:
          approval: manual
          clean_workspace: true
          jobs:
            dependency_check:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
      - update:
          clean_workspace: true
          jobs:
            check_for_updates:
              artifacts:
                - build:
                    source: outdated-dependencies.txt
              tabs:
                Updates: outdated-dependencies.txt
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks list_outdated
            update_package_json:
              artifacts:
                - build:
                    source: package.json
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks update_package_json
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: update
                    job: update_package_json
                    source: package.json
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
            integration:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: update
                    job: update_package_json
                    source: package.json
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_integration
            audit:
              artifacts:
                - build:
                    source: package.json
              tabs:
                'package.json': package.json
              resources:
                - docker
              tasks:
                - fetch:
                    stage: update
                    job: update_package_json
                    source: package.json
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
